namespace ERF.Private;

internal enum EventType
{
    ServerUpdateC = 1,
    PlayerUpdateC = 2,
    PlayerConnectC = 3,
    PlayerChatC = 4,
    PlayerDisconnectC = 5,
    PlayerAttachesUpdateC = 6,
    PlayerTakeItemC = 7,
    PlayerDropItemC = 8,
    PlayerDialogActionC = 9,
    PlayerShootPlayerC = 10,
    PlayerPressPlayerC = 11,
    PlayerShootC = 12,
    PlayerConsoleC = 13,
    PlayerDeathC = 14,
    PlayerRespawnC = 15,
    WorldLoadedC = 16,
    PlayerHitPlayerC = 17,
    PlayerExploreCorpseC = 18,
    PlayerClickObjectC = 19,
    PlayerShootObjectC = 20,
    PlayerUseDoorButtonC = 21,
    PlayerUseItemC = 22,
    PlayerUse914C = 23,
    FineItemC = 24,
    WorldUpdateC = 25,
    PlayerClickGuiC = 26,
    PlayerVoiceC = 27,
    PlayerTeleportElevatorC = 28,
    PlayerSelectItemC = 29,
    ServerConsoleC = 30,
    ServerRestartC = 31,
    PlayerShootNpcC = 32,
    PlayerKeyActionC = 33,
    OnLogC = 34,
}