namespace ACL.Managed;

public enum ScriptErrorType
{
    AsSuccess = 0,
    AsError = -1,
    AsContextActive = -2,
    AsContextNotFinished = -3,
    AsContextNotPrepared = -4,
    AsInvalidArg = -5,
    AsNoFunction = -6,
    AsNotSupported = -7,
    AsInvalidName = -8,
    AsNameTaken = -9,
    AsInvalidDeclaration = -10,
    AsInvalidObject = -11,
    AsInvalidType = -12,
    AsAlreadyRegistered = -13,
    AsMultipleFunctions = -14,
    AsNoModule = -15,
    AsNoGlobalVar = -16,
    AsInvalidConfiguration = -17,
    AsInvalidInterface = -18,
    AsCantBindAllFunctions = -19,
    AsLowerArrayDimensionNotRegistered = -20,
    AsWrongConfigGroup = -21,
    AsConfigGroupIsInUse = -22,
    AsIllegalBehaviourForType = -23,
    AsWrongCallingConv = -24,
    AsBuildInProgress = -25,
    AsInitGlobalVarsFailed = -26,
    AsOutOfMemory = -27,
    AsModuleIsInUse = -28,
}